mail-gun:
  base-url: https://api.mailgun.net/v3/
  username: api
  api-key: "domain api-key"
  source-email: "domain"
sendgrid:
  bearer: "api-key"
  base-url: https://api.sendgrid.com/v3/
  source-email: "source-email"
#server:
#  port: 5000